apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: syslog
  namespace: default
  labels:
    app: syslog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: syslog
  template:
    metadata:
      name: syslog
      labels:
        app: syslog
      annotations:
        networks: '[
        { "name": "calico" }
      ]'
    spec:
      containers:
      - name: logstash
        image: edcop-master:5000/edcop-logstash
        imagePullPolicy: Always
        ports:
        - name: cport-5144
          containerPort: 5144
        resources:
          limits:
            cpu: "2"
        volumeMounts:
          - mountPath: /usr/share/logstash/pipeline/
            name: logstash-syslog-pipeline
          - mountPath: /usr/share/logstash/config
            name: logstash-syslog-config
      volumes:
      - name: logstash-syslog-config
        configMap:
          name: logstash-syslog-config
      - name: logstash-syslog-pipeline
        configMap:
          name: logstash-syslog-pipeline
      restartPolicy: Always
      dnsPolicy: ClusterFirst
