apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: bro-pod
  namespace: default
  labels:
    app: bro-pod
spec:
  selector:
    matchLabels:
      app: bro-pod
  template:
    metadata:
      name: bro-pod
      labels:
        app: bro-pod 
      annotations:
        networks: '[
        { "name": "flannel" },
        { "name": "sriov-vlan-199" },
        { "name": "ovs-plugin" }
      ]'
    spec:
      containers:
      - name: bro
        image: edcop-master:5000/registry/edcop-bro
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts: 
        - mountPath: /usr/local/bro/logs/
          name: bro-logs 
      
      - name: redis
        image: edcop-master:5000/registry/edcop-redis
        imagePullPolicy: Always
        ports:
        - name: cport-6379
          containerPort: 6379
          
      - name: logstash
        image: edcop-master:5000/registry/edcop-logstash-bro
        imagePullPolicy: Always
        ports:
        - name: cport-5044
          containerPort: 5044
       
      - name: filebeat
        image: edcop-master:5000/registry/edcop-filebeat-bro
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /data/bro
          name: bro-logs
          
      volumes:
      - name: bro-logs
        hostPath: 
          path: /data/bro       
          
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      nodeSelector:
        nodetype: worker
