apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: suricata-pod
  namespace: default
  labels:
    app: suricata-pod
spec:
  selector:
    matchLabels:
      app: suricata-pod
  template:
    metadata:
      name: suricata-pod
      labels:
        app: suricata-pod 
      annotations:
        networks: '[
        { "name": "calico" },
        { "name": "inline-1" },
        { "name": "inline-2" }
      ]'
    spec:
      containers:
      - name: suricata
        image: "edcop-master:5000/suricata"
        stdin: true
        command: ["docker-entrypoint.sh"]
        tty: true
        securityContext:
          capabilities:
              add:
                - NET_ADMIN
                - SYS_NICE #Needed for CPU pinning
        volumeMounts:
          - mountPath: /etc/suricata
            name: suricata-config
          - mountPath: /data/suricata
            name: suricata-logs

      - name: redis
        image: edcop-master:5000/edcop-redis
        imagePullPolicy: Always
        ports:
        - name: cport-6379
          containerPort: 6379
          
      - name: logstash
        image: edcop-master:5000/edcop-logstash
        imagePullPolicy: Always
        ports:
        - name: cport-5044
          containerPort: 5044
        resources:
          limits:
            cpu: "2"
        volumeMounts:
          - mountPath: /usr/share/logstash/pipeline/
            name: logstash-suricata-pipeline
          - mountPath: /usr/share/logstash/config
            name: logstash-suricata-config
 
      - name: filebeat
        image: edcop-master:5000/edcop-filebeat
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /suricata
          name: suricata-logs
        - mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
          name: filebeat-suricata-config

      volumes:
      - name: suricata-logs
        emptyDir: {}
      - name: suricata-config
        configMap:
          name: suricata-config
      - name: filebeat-suricata-config
        configMap:
          name: filebeat-suricata-config
      - name: logstash-suricata-config
        configMap:
          name: logstash-suricata-config
      - name: logstash-suricata-pipeline
        configMap:
          name: logstash-suricata-pipeline
          
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      nodeSelector:
        nodetype: worker
