apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: suricata
  namespace: default
  labels:
    app: suricata
spec:
  selector:
    matchLabels:
      app: suricata
  template:
    metadata:
      name: suricata
      labels:
        app: suricata
    spec:
      hostNetwork: true
      containers:
      - name: suricata
        image: suricata
        imagePullPolicy: Never
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts: 
        - mountPath: /var/log/suricata
          name: suricatalogs 
      volumes:
      - name: suricatalogs
        hostPath:
          path: /data/suricata
      restartPolicy: Always
      nodeSelector:
        nodetype: worker
