apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: centos 
  namespace: default
  labels:
    app: centos
spec:
  selector:
    matchLabels:
      app: centos 
  template:
    metadata:
      name: centos 
      labels:
        app: centos 
    spec:
      hostNetwork: true
      containers:
      - name: centos-test 
        image: centos:7
        imagePullPolicy: Always
      restartPolicy: Always
      nodeSelector:
        nodetype: worker
