packetbeat.interfaces.device: net0
packetbeat.interfaces.type: af_packet
packetbeat.interface.buffer_size_mb: 100

packetbeat.protocols.dns:
  ports: [53]
  include_authorities: true
  include_additionals: true

packetbeat.protocols.http:
  ports: [80, 5601, 9200, 8080, 8081, 5000, 8002]

packetbeat.protocols.memcache:
  ports: [11211]

packetbeat.protocols.mysql:
  ports: [3306]

packetbeat.protocols.pgsql:
  ports: [5432]

packetbeat.protocols.redis:
  ports: [6379]

packetbeat.protocols.thrift:
  ports: [9090]

packetbeat.protocols.mongodb:
  ports: [27017]

packetbeat.protocols.cassandra:
  ports: [9042]


processors:
- add_cloud_metadata:

output.redis:
  hosts: ["localhost:6379"]
# password: "my_password"
  key: "packetbeat"
  db: 0
  timeout: 5
