apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: packetbeat
  namespace: default
  labels:
    app: packetbeat
spec:
  selector:
    matchLabels:
      app: packetbeat
  template:
    metadata:
      name: packetbeat
      labels:
        app: packetbeat
      annotations:
        networks: '[
        { "name": "flannel" },
        { "name": "ovs-plugin" },
        { "name": "sriov-vlan-200" }
      ]'
    spec:
      containers:
      - name: packetbeat
        image: registry.edcop.sealingtech.org:5000/registry/edcop-packetbeat
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
      restartPolicy: Always
      nodeSelector:
        nodetype: worker
