apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: sriov-no-vlan-in
plugin: sriov
args: '[
       {
<<<<<<< HEAD
                "if0": "inl0",
=======
                "if0": "eth3",
>>>>>>> 1af9ea75bbdd693f134599c754dbdebee4f7b9b0
                "vf": 0,
                "ipam": {
                  "type": "host-local",
                  "subnet": "10.3.0.0/16",
                  "rangeStart": "10.3.0.10",
                  "rangeEnd": "10.3.0.150"
                }
        }
]'

