apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
  labels:
    component: elasticsearch
spec:
  ports:
  - name: tcp-9200
    protocol: TCP
    port: 9200 
    targetPort: 9200
  selector:
    component: elasticsearch
