apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: DaemonSet
metadata:
  name: suricata 
spec:
  selector:
    matchLabels:
      app: suricata 
  template:
    metadata:
      annotations:
        networks: '[  
        { "name": "flannel" },
        { "name": "sriov-no-vlan-in" },
        { "name": "sriov-no-vlan-out" }
      ]'
      labels:
        app: suricata 
    spec:
      containers:
      - name: suricata 
        image: "registry.edcop.sealingtech.org:5000/registry/edcop-suricata"
        stdin: true
        #command: ["suricata","--af-packet"]
        command: ["docker-entrypoint.sh"]
        tty: true
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /etc/suricata
            name: suricata-config
          - mountPath: /var/log/suricata
          name: suricatalogs
      volumes:
        - name: suricata-config 
          configMap:
             name: suricata-config 
        - name: suricatalogs
        hostPath:
          path: /data/suricata/ 
      restartPolicy: Always
      nodeSelector:
       nodetype: worker
