apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: suricata-inline
  namespace: default
  labels:
    app: suricata-inline
spec:
  selector:
    matchLabels:
      app: suricata-inline
  template:
    metadata:
      name: suricata-inline
      labels:
        app: suricata-inline
      annotations:
        networks: '[
        { "name": "flannel" },
        { "name": "ovs-plugin" },
        { "name": "sriov-no-vlan-in" },
        { "name": "sriov-no-vlan-out" }
      ]'
    spec:
      hostNetwork: true
      containers:
      - name: suricata-inline
        image: suricata-inline
        imagePullPolicy: Never
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts: 
        - mountPath: /var/log/suricata
          name: suricatalogs 
      volumes:
      - name: suricatalogs
        hostPath:
          path: /data/suricata/inline
      restartPolicy: Always
      nodeSelector:
        nodetype: worker

