apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: suricata-pod
  namespace: default
  labels:
    app: suricata-pod
spec:
  selector:
    matchLabels:
      app: suricata-pod
  template:
    metadata:
      name: suricata-pod
      labels:
        app: suricata-pod 
      annotations:
        networks: '[
        { "name": "flannel" },
        { "name": "sriov-no-vlan-in" },
        { "name": "sriov-no-vlan-out" },
        { "name": "ovs-plugin" }
      ]'
    spec:
      containers:
      - name: suricata
        image: edcop-master:5000/registry/edcop-suricata
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
        - mountPath: /var/log/suricata
          name: suricata-logs
      
      - name: redis
        image: edcop-master:5000/registry/edcop-redis
        imagePullPolicy: Always
        ports:
        - name: cport-6379
          containerPort: 6379
          
      - name: logstash
        image: edcop-master:5000/registry/edcop-logstash-suricata
        imagePullPolicy: Always
        ports:
        - name: cport-5044
          containerPort: 5044
       
      - name: filebeat
        image: edcop-master:5000/registry/edcop-filebeat-suricata
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /data/suricata
          name: suricata-logs
          
      volumes:
      - name: suricata-logs
        hostPath:
          path: /data/suricata/       
          
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      nodeSelector:
        nodetype: worker
