apiVersion: v1
data:
  suricata-logstash.conf: |
    input {
      redis {
        host => "localhost"
        key => "suricata"
        data_type => "list"
        codec => json
      }
    }


    output {
      elasticsearch {
        hosts => "elasticsearch:9200"
        manage_template => false
        index => "suricata-%{+YYYY.MM.dd}"
        document_type => "%{[@metadata][type]}"
        codec => json
        #user => logstash_internal
        #password => changeme
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: logstash-suricata-config
  selfLink: /api/v1/namespaces/default/configmaps/logstash-suricata-config
