apiVersion: v1
kind: Service
metadata:
  name: nodelogs
  namespace: default
  labels:
    app: nodelogs
spec:
  ports:
  - name: tcp-9200
    protocol: TCP
    port: 9200 
    targetPort: 9200   
  - name: tcp-9300
    protocol: TCP
    port: 9300 
    targetPort: 9300
  - name: tcp-6397
    protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: nodelogs
  type: LoadBalancer
  sessionAffinity: None
