# EDCOP Elasticsearch Chart values
image:
  repository: edcop-master:5000
networks:
  # Overlay is the name of the default cni network
  overlaynet: calico
volumes:
  # Persistent data location on the host to store Elasticsearch's data
  data: /var/EDCOP/data/esdata
nodeSelector:
  nodetype: worker
elasticsearchConfig:
  env:
    clustername: edcop
    java-opts: -Xms16g -Xmx16g
  limits:
    cpu: 12
    memory: 32Gi

    
