apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: default
  labels:
    component: elasticsearch
    role: master
spec:
  selector: 
    component: elasticsearch
    role: master
  ports:
  - name: tcp-9300
    protocol: TCP
    port: 9300 
    targetPort: 9300
