apiVersion: v1
kind: Service
metadata:
  name: moloch-master
  namespace: default
  labels:
    app: moloch-master
spec:
  ports:
  - name: tcp-8005-8005
    protocol: TCP
    port: 8005
    targetPort: 8005
    nodePort: 30003
  selector:
    app: moloch-master
  type: LoadBalancer
  sessionAffinity: None
