apiVersion: v1
kind: Service
metadata:
  name: {{ template "kibana.fullname" . }}
  namespace: default
  labels:
    app: {{ template "kibana.name" . }}
spec:
  ports:
  - name: tcp-5601-5601
    protocol: TCP
    port: 5601
    targetPort: 5601
    nodePort: 30000
  selector:
    app: {{ template "kibana.fullname" . }}
  type: LoadBalancer
  sessionAffinity: None

