apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-master
  namespace: default
  labels:
    app: elasticsearch-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-master
  template:
    metadata:
      name: elasticsearch-master
      labels:
        app: elasticsearch-master
      annotations:
        networks: '[
        { "name": "flannel" },
        { "name": "ovs-plugin" }
      ]'
    spec:
      containers:
      - name: elasticsearch-master
        image: elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        imagePullPolicy: Never
        securityContext:
          privileged: true
        volumeMounts: 
        - mountPath: /usr/share/elasticsearch/data
          name: esdata
      volumes:
      - name: esdata
        hostPath:
          path: /esdata
            
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      nodeSelector:
        nodetype: master

