apiVersion: v1
data:
  local-logger.bro: |
    ##! Local site policy loaded only by the logger if Bro is running as a cluster.
  local-manager.bro: |
    ##! Local site policy loaded only by the manager if Bro is running as a cluster.
  local-proxy.bro: |
    ##! Local site policy loaded only by the proxies if Bro is running as a cluster.
  local-worker.bro: '##! Local site policy loaded only by the workers if Bro is running
    as a cluster.'
  local.bro: |
    ##! Local site policy. Customize as appropriate.
    ##!
    ##! This file will not be overwritten when upgrading or reinstalling!

    # This script logs which scripts were loaded during each run.
    @load misc/loaded-scripts

    # Apply the default tuning scripts for common tuning settings.
    @load tuning/defaults

    # Estimate and log capture loss.
    @load misc/capture-loss

    # Enable logging of memory, packet and lag statistics.
    @load misc/stats

    # Load the scan detection script.
    @load misc/scan

    # Detect traceroute being run on the network. This could possibly cause
    # performance trouble when there are a lot of traceroutes on your network.
    # Enable cautiously.
    #@load misc/detect-traceroute

    # Generate notices when vulnerable versions of software are discovered.
    # The default is to only monitor software found in the address space defined
    # as "local".  Refer to the software framework's documentation for more
    # information.
    @load frameworks/software/vulnerable

    # Detect software changing (e.g. attacker installing hacked SSHD).
    @load frameworks/software/version-changes

    # This adds signatures to detect cleartext forward and reverse windows shells.
    @load-sigs frameworks/signatures/detect-windows-shells

    # Load all of the scripts that detect software in various protocols.
    @load protocols/ftp/software
    @load protocols/smtp/software
    @load protocols/ssh/software
    @load protocols/http/software
    # The detect-webapps script could possibly cause performance trouble when
    # running on live traffic.  Enable it cautiously.
    #@load protocols/http/detect-webapps

    # This script detects DNS results pointing toward your Site::local_nets
    # where the name is not part of your local DNS zone and is being hosted
    # externally.  Requires that the Site::local_zones variable is defined.
    @load protocols/dns/detect-external-names

    # Script to detect various activity in FTP sessions.
    @load protocols/ftp/detect

    # Scripts that do asset tracking.
    @load protocols/conn/known-hosts
    @load protocols/conn/known-services
    @load protocols/ssl/known-certs

    # This script enables SSL/TLS certificate validation.
    @load protocols/ssl/validate-certs

    # This script prevents the logging of SSL CA certificates in x509.log
    @load protocols/ssl/log-hostcerts-only

    # Uncomment the following line to check each SSL certificate hash against the ICSI
    # certificate notary service; see http://notary.icsi.berkeley.edu .
    # @load protocols/ssl/notary

    # If you have libGeoIP support built in, do some geographic detections and
    # logging for SSH traffic.
    @load protocols/ssh/geo-data
    # Detect hosts doing SSH bruteforce attacks.
    @load protocols/ssh/detect-bruteforcing
    # Detect logins using "interesting" hostnames.
    @load protocols/ssh/interesting-hostnames

    # Detect SQL injection attacks.
    @load protocols/http/detect-sqli

    #### Network File Handling ####

    # Enable MD5 and SHA1 hashing for all files.
    @load frameworks/files/hash-all-files

    # Detect SHA1 sums in Team Cymru's Malware Hash Registry.
    @load frameworks/files/detect-MHR

    # Uncomment the following line to enable detection of the heartbleed attack. Enabling
    # this might impact performance a bit.
    # @load policy/protocols/ssl/heartbleed

    # Uncomment the following line to enable logging of connection VLANs. Enabling
    # this adds two VLAN fields to the conn.log file.
    # @load policy/protocols/conn/vlan-logging

    # Uncomment the following line to enable logging of link-layer addresses. Enabling
    # this adds the link-layer address for each connection endpoint to the conn.log file.
    # @load policy/protocols/conn/mac-logging

    # Uncomment the following line to enable the SMB analyzer.  The analyzer
    # is currently considered a preview and therefore not loaded by default.
    # @load policy/protocols/smb

    @load policy/tuning/json-logs
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"local-logger.bro":"##! Local site policy loaded only by the logger if Bro is running as a cluster.\n","local-manager.bro":"##! Local site policy loaded only by the manager if Bro is running as a cluster.\n","local-proxy.bro":"##! Local site policy loaded only by the proxies if Bro is running as a cluster.\n","local-worker.bro":"##! Local site policy loaded only by the workers if Bro is running as a cluster.","local.bro":"##! Local site policy. Customize as appropriate.\n##!\n##! This file will not be overwritten when upgrading or reinstalling!\n\n# This script logs which scripts were loaded during each run.\n@load misc/loaded-scripts\n\n# Apply the default tuning scripts for common tuning settings.\n@load tuning/defaults\n\n# Estimate and log capture loss.\n@load misc/capture-loss\n\n# Enable logging of memory, packet and lag statistics.\n@load misc/stats\n\n# Load the scan detection script.\n@load misc/scan\n\n# Detect traceroute being run on the network. This could possibly cause\n# performance trouble when there are a lot of traceroutes on your network.\n# Enable cautiously.\n#@load misc/detect-traceroute\n\n# Generate notices when vulnerable versions of software are discovered.\n# The default is to only monitor software found in the address space defined\n# as \"local\".  Refer to the software framework's documentation for more\n# information.\n@load frameworks/software/vulnerable\n\n# Detect software changing (e.g. attacker installing hacked SSHD).\n@load frameworks/software/version-changes\n\n# This adds signatures to detect cleartext forward and reverse windows shells.\n@load-sigs frameworks/signatures/detect-windows-shells\n\n# Load all of the scripts that detect software in various protocols.\n@load protocols/ftp/software\n@load protocols/smtp/software\n@load protocols/ssh/software\n@load protocols/http/software\n# The detect-webapps script could possibly cause performance trouble when\n# running on live traffic.  Enable it cautiously.\n#@load protocols/http/detect-webapps\n\n# This script detects DNS results pointing toward your Site::local_nets\n# where the name is not part of your local DNS zone and is being hosted\n# externally.  Requires that the Site::local_zones variable is defined.\n@load protocols/dns/detect-external-names\n\n# Script to detect various activity in FTP sessions.\n@load protocols/ftp/detect\n\n# Scripts that do asset tracking.\n@load protocols/conn/known-hosts\n@load protocols/conn/known-services\n@load protocols/ssl/known-certs\n\n# This script enables SSL/TLS certificate validation.\n@load protocols/ssl/validate-certs\n\n# This script prevents the logging of SSL CA certificates in x509.log\n@load protocols/ssl/log-hostcerts-only\n\n# Uncomment the following line to check each SSL certificate hash against the ICSI\n# certificate notary service; see http://notary.icsi.berkeley.edu .\n# @load protocols/ssl/notary\n\n# If you have libGeoIP support built in, do some geographic detections and\n# logging for SSH traffic.\n@load protocols/ssh/geo-data\n# Detect hosts doing SSH bruteforce attacks.\n@load protocols/ssh/detect-bruteforcing\n# Detect logins using \"interesting\" hostnames.\n@load protocols/ssh/interesting-hostnames\n\n# Detect SQL injection attacks.\n@load protocols/http/detect-sqli\n\n#### Network File Handling ####\n\n# Enable MD5 and SHA1 hashing for all files.\n@load frameworks/files/hash-all-files\n\n# Detect SHA1 sums in Team Cymru's Malware Hash Registry.\n@load frameworks/files/detect-MHR\n\n# Uncomment the following line to enable detection of the heartbleed attack. Enabling\n# this might impact performance a bit.\n# @load policy/protocols/ssl/heartbleed\n\n# Uncomment the following line to enable logging of connection VLANs. Enabling\n# this adds two VLAN fields to the conn.log file.\n# @load policy/protocols/conn/vlan-logging\n\n# Uncomment the following line to enable logging of link-layer addresses. Enabling\n# this adds the link-layer address for each connection endpoint to the conn.log file.\n# @load policy/protocols/conn/mac-logging\n\n# Uncomment the following line to enable the SMB analyzer.  The analyzer\n# is currently considered a preview and therefore not loaded by default.\n# @load policy/protocols/smb\n\n@load policy/tuning/json-logs\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"bro-site-config","namespace":"default","selfLink":"/api/v1/namespaces/default/configmaps/bro-site-config"}}
  creationTimestamp: null
  name: bro-site-config
  selfLink: /api/v1/namespaces/default/configmaps/bro-site-config
