apiVersion: v1
data:
  packetbeat.conf: "input {\n  redis {\n    host => \"localhost\"\n    key => \"packetbeat\"\n
    \   data_type => \"list\"\n    codec => json\n    add_field => {\"tool\" => \"packetbeat\"}\n
    \ }\n}\n\noutput {\n  elasticsearch {\n    hosts => \"elasticsearch:9200\"\n    manage_template
    => false\n    index => \"packetbeat-%{+YYYY.MM.dd}\" \n    document_type => \"%{[@metadata][type]}\"\n
    \   #user => logstash_internal\n    #password => changeme\n  }\n}\n\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"packetbeat.conf":"input {\n  redis {\n    host =\u003e \"localhost\"\n    key =\u003e \"packetbeat\"\n    data_type =\u003e \"list\"\n    codec =\u003e json\n    add_field =\u003e {\"tool\" =\u003e \"packetbeat\"}\n  }\n}\n\noutput {\n  elasticsearch {\n    hosts =\u003e \"elasticsearch:9200\"\n    manage_template =\u003e false\n    index =\u003e \"packetbeat-%{+YYYY.MM.dd}\" \n    document_type =\u003e \"%{[@metadata][type]}\"\n    #user =\u003e logstash_internal\n    #password =\u003e changeme\n  }\n}\n\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"logstash-packetbeat-config","namespace":"default","selfLink":"/api/v1/namespaces/default/configmaps/logstash-packetbeat-config"}}
  creationTimestamp: null
  name: logstash-packetbeat-config
  selfLink: /api/v1/namespaces/default/configmaps/logstash-packetbeat-config
