# EDCOP Kibana Chart values
image:
  # Basic image: docker.elastic.co/kibana/kibana:6.1.4
  kibana: edcop-master:5000/kibana
networks:
  # Overlay is the name of the default cni network
  overlay: calico
nodeSelector:
  nodetype: master
ingress:
  # Enter the FQDN of your host
  host: <$FQDN>  
