apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  namespace: default
  labels:
    app: elasticsearch-master
spec:
  ports:
  - name: tcp-9200-9200
    protocol: TCP
    port: 9200 
    targetPort: 9200
  selector:
    app: elasticsearch-master
  type: LoadBalancer
  sessionAffinity: None
