apiVersion: v1
kind: Service
metadata:
  name: nodelogs
  namespace: default
  labels:
    app: nodelogs
spec:
  ports:
  - name: tcp-9200
    protocol: TCP
    port: 9200 
    targetPort: 9200   
  selector:
    app: nodelogs
  type: LoadBalancer
  sessionAffinity: None
