apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "suricata.fullname" . }}
  namespace: default
  labels:
    app: {{ template "suricata.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "suricata.name" . }}
  template:
    metadata:
      name: {{ template "suricata.name" . }}
      labels:
        app: {{ template "suricata.name" . }}
      annotations:
        networks: '[
        { "name": "{{  .Values.networks.overlaynet }}" },
        { "name": "{{  .Values.networks.net1 }}" },
        { "name": "{{  .Values.networks.net2 }}" }
      ]'
    spec:
      containers:
      - name: suricata
        image: {{ .Values.image.repository }}/suricata
        stdin: true
        command: ["docker-entrypoint.sh"]
        tty: true
        securityContext:
          capabilities:
              add:
                - NET_ADMIN
                - SYS_NICE #Needed for CPU pinning
        volumeMounts:
          - mountPath: /etc/suricata
            name: suricata-config
          - mountPath: /data/suricata
            name: suricata-logs
        resources:
          limits:
            cpu: "{{ .Values.suricataConfig.limits.cpu }}"
            memory: "{{ .Values.suricataConfig.limits.memory }}"

      - name: redis
        image: {{ .Values.image.repository }}/redis
        imagePullPolicy: Always
        ports:
        - name: cport-6379
          containerPort: 6379
        resources:
          limits:
            cpu: "{{ .Values.redisConfig.limits.cpu }}"
            memory: "{{ .Values.redisConfig.limits.memory }}"

      - name: logstash
        image: {{ .Values.image.repository }}/logstash
        imagePullPolicy: Always
        ports:
        - name: cport-5044
          containerPort: 5044
        resources:
          limits:
            cpu: "{{ .Values.logstashConfig.limits.cpu }}"
            memory: "{{ .Values.logstashConfig.limits.memory }}"
        volumeMounts:
          - mountPath: /usr/share/logstash/pipeline/
            name: logstash-suricata-pipeline
          - mountPath: /usr/share/logstash/config
            name: logstash-suricata-config

      - name: filebeat
        image: {{ .Values.image.repository }}/filebeat
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /suricata
          name: suricata-logs
        - mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
          name: filebeat-suricata-config

      volumes:
      - name: suricata-logs
        hostPath:
          path: {{ .Values.volumes.logs.hostPath }}
      - name: suricata-config
        configMap:
          name: {{ template "suricata.fullname" . }}-config
      - name: filebeat-suricata-config
        configMap:
          name: filebeat-{{ template "suricata.fullname" . }}-config
      - name: logstash-suricata-config
        configMap:
          name: logstash-{{ template "suricata.fullname" . }}-config
      - name: logstash-suricata-pipeline
        configMap:
          name: logstash-{{ template "suricata.fullname" . }}-pipeline

      restartPolicy: Always
      dnsPolicy: ClusterFirst
      nodeSelector:
        nodetype: worker
