# EDCOP Bro Chart values
image:
  repository: edcop-master:5000
resources:
  limits:
    cpu: 2
networks:
  # Overlay is the name of the default cni network
  overlay-net: calico
  # Net 1 is the name of the first sriov interface
  passive-net: passive
volumes:
  # Persistent data location on the host to store suricata's logs
  logs:
    spool: 
      hostPath: /var/EDCOP/data/logs/bro/spool
    logs: 
      hostPath: /var/EDCOP/data/logs/bro/logs
    
nodeSelector:
  nodetype: worker
