apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: moloch-nodes
  namespace: default
  labels:
    app: moloch-nodes
spec:
  selector:
    matchLabels:
      app: moloch-nodes
  template:
    metadata:
      name: moloch-nodes
      labels:
        app: moloch-nodes
      annotations:
        networks: '[
        { "name": "flannel" },
        { "name": "sriov-vlan-202" }
      ]'
    spec:
      containers:
      - name: moloch-nodes
        image: registry.edcop.sealingtech.org:5000/registry/edcop-moloch
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 8005
        volumeMounts: 
        - mountPath: /data/moloch/logs
          name: molochlogs 
        - mountPath: /data/moloch/raw
          name: molochraw
      volumes:
      - name: molochlogs
        hostPath:
          path: /data/moloch/logs
      - name: molochraw
        hostPath:
          path: /data/moloch/raw
      restartPolicy: Always
      nodeSelector:
        nodetype: worker

