apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: kibana-web-ui
 namespace: kube-system
 annotations:
   kubernetes.io/ingress.class: traefik
   traefik.frontend.rule.type: PathPrefixStrip
   # ingress.kubernetes.io/auth-type: "basic"
   # ingress.kubernetes.io/auth-secret: "ingress-auth"
spec:
 rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /kibana
        backend:
          serviceName: kibana-svc
          servicePort: 5601
