apiVersion: v1
data:
  overrides.js: |-
    window.monocular = {
      overrides: {
        googleAnalyticsId: 'UA-XXXXXX-X',
        appName: 'Monocular',
        backendHostname: '/api',
        releasesEnabled: true
      }
    };
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: alternating-badger-monocular
    chart: monocular-0.5.0
    heritage: Tiller
    release: alternating-badger
  name: alternating-badger-monocular-ui-config
  selfLink: /api/v1/namespaces/default/configmaps/alternating-badger-monocular-ui-config
