apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
  labels:
    app: kibana
spec:
  ports:
  - name: tcp-5601-5601
    protocol: TCP
    port: 5601
    targetPort: 5601
    nodePort: 30002
  selector:
    app: kibana
  type: LoadBalancer
  sessionAffinity: None
