apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: {{ template "syslog.fullname" . }}
  namespace: default
  labels:
    app: {{ template "syslog.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ template "syslog.name" . }}
  template:
    metadata:
      name: {{ template "syslog.name" . }}
      labels:
        app: {{ template "syslog.name" . }}
      annotations:
        networks: '[
        { "name": "{{ .Values.networks.overlay }}" }
      ]'
    spec:
      containers:
      - name: logstash
        image: {{ .Values.images.logstash }}
        imagePullPolicy: Always
        ports:
        - name: cport-5144
          containerPort: 5144
        resources:
          limits:
            cpu: "{{ .Values.logstashConfig.limits.cpu }}"
            memory: "{{ .Values.logstashConfig.limits.memory }}"
        volumeMounts:
          - mountPath: /usr/share/logstash/pipeline/
            name: logstash-syslog-pipeline
          - mountPath: /usr/share/logstash/config
            name: logstash-syslog-config

      volumes:
      - name: logstash-syslog-config
        configMap:
          name: logstash-{{ template "syslog.fullname" . }}-config
      - name: logstash-syslog-pipeline
        configMap:
          name: logstash-{{ template "syslog.fullname" . }}-pipeline
      restartPolicy: Always
      dnsPolicy: ClusterFirst
