apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: bro-pod
  namespace: default
  labels:
    app: bro-pod
spec:
  selector:
    matchLabels:
      app: bro-pod
  template:
    metadata:
      name: bro-pod
      labels:
        app: bro-pod 
      annotations:
        networks: '[
        { "name": "calico" },
        { "name": "sriov-passive-novlan" }
      ]'
    spec:
      containers:
      - name: bro
        image: edcop-master:5000/edcop-bro
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
              - NET_ADMIN 
              - SYS_NICE #Used for CPU pinning
        volumeMounts:
        - mountPath: /usr/local/bro/logs/
          name: bro-logs 
        - mountPath: /usr/local/bro/etc/
          name: bro-etc-config 
        - mountPath: /usr/local/bro/share/bro/site/
          name: bro-site-config 
        - mountPath: /usr/local/bro/spool/
          name: bro-spool
      
      - name: redis
        image: edcop-master:5000/registry/edcop-redis
        imagePullPolicy: Always
        ports:
        - name: cport-6379
          containerPort: 6379
          
      - name: logstash
        image: edcop-master:5000/registry/edcop-logstash
        imagePullPolicy: Always
        ports:
        - name: cport-5044
          containerPort: 5044
        resources:
          limits:
            cpu: "8"
        volumeMounts:
        - mountPath: /usr/share/logstash/pipeline/bro.conf
          subPath: bro.conf
          name: logstash-bro-config
        - mountPath: /usr/share/logstash/config/jvm.options
          subPath: jvm.options
          name: logstash-bro-jvm

      - name: filebeat
        image: edcop-master:5000/registry/edcop-filebeat
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /bro/
          name: bro-spool
        - mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
          name: filebeat-bro-config
          
      volumes:
      - name: bro-logs
        hostPath: 
          path: /var/EDCOP/logs/bro/logs       
      - name: bro-etc-config
        configMap:
          name: bro-etc-config
      - name: bro-site-config
        configMap:
          name: bro-site-config
      - name: bro-spool
        hostPath: 
          path: /var/EDCOP/logs/bro/spool
      - name: filebeat-bro-config
        configMap:
          name: filebeat-bro-config
      - name: logstash-bro-config
        configMap:
          name: logstash-bro-config
      - name: logstash-bro-jvm
        configMap:
          name: logstash-bro-jvm
          
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      nodeSelector:
        nodetype: worker
