apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: sriov-vlan-201
plugin: sriov
args: '[
       {
                "if0": "eth5",
                "vf": 0,
                "vlan": 201,
                "ipam": {
                  "type": "host-local",
                  "subnet": "10.3.0.0/16",
                  "rangeStart": "10.3.0.10",
                  "rangeEnd": "10.3.0.150"
                }
        }
]'
