apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: sriov-passive-novlan-packetbeat
plugin: sriov
args: '[
       {
                "if0": "pas0",
                "vf": 1,
                "ipam": {
                  "type": "host-local",
                  "subnet": "10.51.0.0/16",
                  "rangeStart": "10.51.0.10",
                  "rangeEnd": "10.51.0.150"
                }
        }
]'
